const Avatars = [
  { id: 'actress', avatar: require('./001-actress.svg') },
  { id: 'burglar', avatar: require('./002-burglar.svg') },
  { id: 'mechanic', avatar: require('./003-mechanic.svg') },
  { id: 'operator1', avatar: require('./004-operator-1.svg') },
  { id: 'reaper', avatar: require('./005-reaper.svg') },
  { id: 'mime', avatar: require('./006-mime.svg') },
  { id: 'soldier', avatar: require('./007-soldier.svg') },
  { id: 'surgeon', avatar: require('./008-surgeon.svg') },
  { id: 'student', avatar: require('./009-student.svg') },
  { id: 'basketballPlayer', avatar: require('./010-basketball-player.svg') },
  { id: 'farmer', avatar: require('./011-farmer.svg') },
  { id: 'steampunk', avatar: require('./012-steampunk.svg') },
  { id: 'mariachi', avatar: require('./013-mariachi.svg') },
  { id: 'doctor', avatar: require('./014-doctor.svg') },
  { id: 'gothic', avatar: require('./015-gothic.svg') },
  { id: 'robot', avatar: require('./016-robot.svg') },
  { id: 'pilot', avatar: require('./017-pilot.svg') },
  { id: 'caveman', avatar: require('./018-caveman.svg') },
  { id: 'safari', avatar: require('./019-safari.svg') },
  { id: 'chef', avatar: require('./020-chef.svg') },
  { id: 'bunny', avatar: require('./021-bunny.svg') },
  { id: 'woman', avatar: require('./022-woman.svg') },
  { id: 'businessman', avatar: require('./023-businessman.svg') },
  { id: 'builder', avatar: require('./024-builder.svg') },
  { id: 'monster', avatar: require('./025-monster.svg') },
  { id: 'operator', avatar: require('./026-operator.svg') },
  { id: 'baseballPlayer', avatar: require('./027-baseball-player.svg') },
  { id: 'magician', avatar: require('./028-magician.svg') },
  { id: 'bear', avatar: require('./029-bear.svg') },
  { id: 'witch', avatar: require('./030-witch.svg') },
  { id: 'pirate', avatar: require('./031-pirate.svg') },
  { id: 'wrestler', avatar: require('./032-wrestler.svg') },
  { id: 'sumo', avatar: require('./033-sumo.svg') },
  { id: 'scubaDiver', avatar: require('./034-scuba-diver.svg') },
  { id: 'zombie', avatar: require('./035-zombie.svg') },
  { id: 'policewoman', avatar: require('./036-policewoman.svg') },
  { id: 'frankenstein', avatar: require('./037-frankenstein.svg') },
  { id: 'grandfather', avatar: require('./038-grandfather.svg') },
  { id: 'grandmother', avatar: require('./039-grandmother.svg') },
  { id: 'viking', avatar: require('./040-viking.svg') },
  { id: 'cowboy', avatar: require('./041-cowboy.svg') },
  { id: 'superhero', avatar: require('./042-superhero.svg') },
  { id: 'santaClaus', avatar: require('./043-santa-claus.svg') },
  { id: 'fireman', avatar: require('./044-fireman.svg') },
  { id: 'ninja', avatar: require('./045-ninja.svg') },
  { id: 'astronaut', avatar: require('./046-astronaut.svg') },
  { id: 'clown', avatar: require('./047-clown.svg') },
  {
    id: 'americanFootballPlayer',
    avatar: require('./048-american-football-player.svg')
  },
  { id: 'dracula', avatar: require('./049-dracula.svg') },
  { id: 'skater', avatar: require('./050-skater.svg') }
];
export default Avatars;
